install: "./publish_from_travis.sh"
env:
  global:
    secure: hrfBYK9YXs0rJJvr3zbIFFt7E11KdbtTzbSYgvULEhVgRwXscKRj/x9eUrfwQRBWnR8WjhKglsx+UT+278xHV3FQHqUgkgwT5VMwfiHFUUaqOgXD+sS9SLLA4GmgFKeS1iukgrl87QqBWXoxhCZGqgHcPIApySAEeOvvQUKbO+M=
