source 'https://rubygems.org'

gem 'nanoc', git: 'https://github.com/froderik/nanoc.git'
gem 'adsf'
gem 'kramdown'
gem 'haml'
gem 'nokogiri'
gem 'builder'
gem 'simple-rss'
gem 'htmlentities'
gem 'travis'
